# Manual call Publish-Artifact with current version
name: Comment-Publish-Artifact
on:
  issue_comment:
    types: [created]

jobs:
  dispatch_publish_artifact:
    if: |
      github.event_name == 'issue_comment' &&
      startsWith(github.event.comment.body, '@secretlint publish artifact')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Current Version
        shell: bash -ex {0}
        run: |
          echo "${{github.event.comment.author_association}}"
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "::set-env name=CURRENT_VERSION::${CURRENT_VERSION}"
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          event-type: publish-artifact
          client-payload: '{"version": "${{ env.CURRENT_VERSION }}"}'
