name: Push Docker Image

on:
  push:
    branches:
    - master
    tags:
      - "*"

env:
  DOCKER_BASE_NAME: docker.pkg.github.com/${{ github.repository }}/secretlint
  DOCKER_HUB_BASE_NAME: secretlint/secretlint

jobs:
  hadolint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - run: brew install hadolint
    - run: hadolint ./Dockerfile
      working-directory: ./docker

  push:
    runs-on: ubuntu-18.04
    needs: hadolint
    steps:
    - uses: actions/checkout@v2
    - name: Set env
      run: |
        if [ "${{ github.event_name }}" = 'release' ]; then
            export TAG_NAME="${{ github.event.release.tag_name }}"
        else
            export TAG_NAME="latest"
        fi
        echo "::set-env name=PKG_TAG::${DOCKER_BASE_NAME}:${TAG_NAME}"
        echo "::set-env name=HUB_TAG::${DOCKER_HUB_BASE_NAME}:${TAG_NAME}"


    - name: Build image
      run: |
        docker build . -t "${PKG_TAG}"
        docker tag "${PKG_TAG}" "${HUB_TAG}"
      working-directory: ./docker
    - name: Print version
      run: |
        docker run --rm ${PKG_TAG} --version
      working-directory: ./docker
    - name: Scan image
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock \
          -v ${HOME}/.cache:/root/.cache aquasec/trivy:latest --exit-code 1 ${PKG_TAG}
      working-directory: ./docker

    - name: Login to Registries
      if: github.event_name != 'pull_request'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
      run: |
        echo "${GITHUB_TOKEN}" | docker login docker.pkg.github.com -u azu --password-stdin
        echo "${DOCKER_HUB_TOKEN}" | docker login -u efcl --password-stdin

    - name: Push to GitHub Packages
      if: github.event_name != 'pull_request'
      run: docker push "${PKG_TAG}"

    - name: Push to Docker Hub
      if: github.event_name != 'pull_request'
      run: docker push "${HUB_TAG}"
