name: test
on:
  push:
    branches-ignore:
      - gh-pages
  pull_request:
env:
  CI: true
jobs:
  hadolint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: brew install hadolint
      - run: hadolint ./Dockerfile
        working-directory: ./publish/docker

  test:
    name: "Test on Node.js ${{ matrix.node_version }} OS: ${{matrix.os}}"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-18.04]
        node_version: [10, 12]
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install
        run: yarn install
      - name: Test
        run: yarn ci
